### PR TITLE
Create .gitignore and Makefiles

### PR DESCRIPTION
**Pull request by mmorella-dev**
To build robust regulation, you need robust build tools!

:^)

### CODE REVIEW

**Review by jflo — APPROVED** [review]
Thank you for an actual constructive contribution, citizen.

**Comment by mmorella-dev** [comment]
Just doing my part!

Fuck cryptocurrency.

**Comment by Bowero** [comment]
I think this is a great suggestion, but if we are adding the Makefile, we also need to update the `README.md` with instructions.

**Comment by Bowero** [comment]
Did you remove the upstream branch on purpose?

**Comment by mmorella-dev** [comment]
> Did you remove the upstream branch on purpose?
@Bowero 

No, just sloppy GitHub use on my part! I tend to delete my own forks when my changes get merged, so my stale branches don't keep rattling around the network. Especially for this PR, which I only did as a joke.

It looks like @jflo *approved* the change, but didn't merge it.

**Comment by Bowero** [comment]
Everyone can approve a pull request on this repository, so that doesn't mean a lot indeed.

I'd actually love to see this get merged, as I think it would be very helpful if changes were to be made and pushed. I don't know if that's how the legislators intend to use this repository, but it would be outstanding if they did.

**Pull request closed without merging**
