### PR TITLE
Add Linux kernel

### PR DESCRIPTION
**Pull request by swift502**
Thank you for your consideration.

### CODE REVIEW

**Review by CrosRoad95 — APPROVED** [review]
i approve

**Review by stoneage-mta — APPROVED** [review]
LGTM!

**Review by aesedepece — APPROVED** [review]

**Comment by piperswe** [comment]
> Files changed: ∞

🤔

**Review by jerrywardlow — APPROVED** [review]

**Comment by coip** [comment]
Do you think there is good enough coverage to accept this without runtime bugs? We seem to have so many already.

**Review by ScriptAlchemist — CHANGES_REQUESTED** [review]
waste of time pr

**Review by cryptofyre — APPROVED** [review]
i donald trump approve this message

**Review by Maximal98 — COMMENTED** [review]
amazing, merge immeadeatly

**Comment by garrettgu10** [comment]
LGTM 👍

**Review by TheEssem — APPROVED** [review]
Makes this much more usable, LGTM

**Review by r-angeles — COMMENTED** [review]
I believe this may cause some conflicts with the pull request #97, not taking into account the addition of [Linux Kernel's licenses](https://github.com/swift502/RFIA-bill-Linux/tree/a314cdcccec3cc574e407185ccb491ab72d195dc/linux-master/LICENSES/preferred). If we're to discard the use of conventional licenses (eg. MIT, GPL), I think a further discussion is much needed.

A repo that would be helpful in deciding a new unconventional license for the RFIA Bill. https://github.com/ErikMcClure/bad-licenses

**Review by kittibyte — APPROVED** [review]
looks pretty good! hoping to see this merged soon

**Comment by coolswag88** [comment]
i love linux

**Review by coolswag88 — APPROVED** [review]

**Review by notnullnotvoid — APPROVED** [review]

**Comment by ChenYFan** [comment]
火钳刘明，不得不说在法案库前面上Linuxkernel确实是一个活久见的操作

**Review by ChenYFan — APPROVED** [review]

**Pull request closed without merging**
