### PR TITLE
🛠 Add build tools and README.md

### PR DESCRIPTION
**Pull request by mmorella-dev**
Continued from PR https://github.com/responsible-financial-innovation-act22/RFIA-bill/pull/18, closed prematurely due to user error.

A bold platform for America's financial infrastructure requires a bold project infrastructure!

### CODE REVIEW

**Review by Bowero — COMMENTED** [review]
I'm on mobile, so my apologies in advance for any errors.

First of all, I love this contribution and I think it'd be extremely meaningful to get this merged, especially if the legislators intend to push their changes here as well. Perhaps it could even be combined with GitHub Actions to automatically run the `Makefile` once changes are made to bill.

I do have a few minor things I'm not sure about:

1. I completely understand why you removed the bill from the `README.md` and moved it to the other Markdown file, but I think it would be more useful for the general public if the bill were to be in the `README.md`
2. The `.gitignore` seems to exclude `.pdf` files, but I think it'd be very useful to always have the latest PDF version, since that's now included as well. This would also make things easier for the general public again.

What are your thoughts on this?

**Comment by mikuhl-dev** [comment]
It would be interesting to be able to build the pdf from the markdown source. README can have link to the source file for reading instead of having to load such a large file visiting this repository.

**Comment by Bowero** [comment]
> It would be interesting to be able to build the pdf from the markdown source. README can have link to the source file for reading instead of having to load such a large file visiting this repository.

I had not realized that you can't generate the pdf in a meaningful way if the installation details are in the same file as the bill. Good catch!

**Comment by mikuhl-dev** [comment]
I am looking over the pdf we have now trying to wrack my brain with what kind of format they use, honestly seems like they hit the randomize button on Microsoft Word. Maybe someone else knows.

**Comment by AlexanderPuckhaber** [comment]
> The `.gitignore` seems to exclude `.pdf` files, but I think it'd be very useful to always have the latest PDF version, since that's now included as well. This would also make things easier for the general public again.

Sure, but the compiled `.pdf` would clutter up the commits. Usually compiled things aren't included in commits. Maybe putting it in "Releases" and having a download link, or publishing it on GitHub pages would work better.

**Comment by mikuhl-dev** [comment]
> Maybe putting it in "Releases" and having a download link, or publishing it on GitHub pages would work better.

Can use Github Actions for this too.

**Comment by ademidun** [comment]
I love the idea behind this PR @morellam-dev ! Editing the bill as a markdown then compiling it to PDF is a really great idea!

A couple of comments:

1. It looks like this PR removes the `README.md` file? I agree with @Bowero comment: https://github.com/responsible-financial-innovation-act22/RFIA-bill/pull/26#pullrequestreview-1017678339, the `README.md` should not be deleted. It should be changed to provide instructions on how to use this repo
2. The actual bill can go into an `RFIA.md` file.
3. Here is my suggestion:
    1. Approve #11 -> Approve #12 -> Merge `main` into #26 -> Move `README.md` into `RFIA.md` and rewrite `README.md` with instructions how to: 1. View the `RFIA.md` 2. View the `RFIA.md` 3. Build the `RFIA.md` into a PDF

Also, does anyone know if @responsible-financial-innovation-act22 is going to approve any of our PRs?

**Comment by Bowero** [comment]
> Also, does anyone know if @responsible-financial-innovation-act22 is going to approve any of our PRs?

Judging by the fact they needed 3 commits to get the bill correctly in the repository, and the fact that `RFIA.md` still has all of that mess in it, I think it's fair to say that there's a reasonable chance they won't be merging anything.

I really hope that they will however, because it would be such an enormous step forward in the area of legislation. If you really care about democracy, this should be a development you should be really excited about.

I actually couldn't care less about the bill itself. As a matter of fact, I'm not even an American citizen. I just want this development to succeed.

**Comment by ademidun** [comment]
> I just want this development to succeed.

Agreed: I'm proposing we fork this repo and make a new one. What do you think? See: https://github.com/responsible-financial-innovation-act22/RFIA-bill/issues/41

**Pull request closed without merging**
